# Generated by Django 4.2.5 on 2023-09-27 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ref', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/sign/dzecko_image_bucket/gato.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJkemVja29faW1hZ2VfYnVja2V0L2dhdG8uanBnIiwiaWF0IjoxNjk1ODI0MzkzLCJleHAiOjE3MjczNjAzOTN9.IIMx1Zg5Vbfniiecnx6SuXAK9UjnonxQcr9LENSEhRM&t=2023-09-27T14%3A19%3A48.828Z', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.ManyToManyField(blank=True, related_name='option_images', to='main.media')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('images', models.ManyToManyField(blank=True, related_name='type_images', to='main.media')),
            ],
        ),
        migrations.CreateModel(
            name='Revetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('description', models.TextField()),
                ('images', models.ManyToManyField(blank=True, related_name='revetment_images', to='main.media')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('ambiance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ambiance')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('furnitures', models.ManyToManyField(related_name='orders', to='main.furniture')),
                ('images', models.ManyToManyField(blank=True, related_name='order_images', to='main.media')),
                ('options', models.ManyToManyField(related_name='orders', to='main.option')),
                ('questions', models.ManyToManyField(related_name='orders', to='main.question')),
                ('revetment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.revetement')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ref', models.CharField(blank=True, max_length=50, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('images', models.ManyToManyField(blank=True, related_name='furniture_type_images', to='main.media')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type')),
            ],
        ),
        migrations.AddField(
            model_name='furniture',
            name='furniture_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.furnituretype'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='furniture_images', to='main.media'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.type'),
        ),
        migrations.AddField(
            model_name='ambiance',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='ambiance_images', to='main.media'),
        ),
    ]
