# Generated by Django 4.2.5 on 2023-09-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_value', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='orders', to='main.color'),
        ),
    ]
