# Generated by Django 4.2.5 on 2023-10-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_color_order_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_url',
            field=models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/sign/dzecko_image_bucket/gato.jpg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJkemVja29faW1hZ2VfYnVja2V0L2dhdG8uanBnIiwiaWF0IjoxNjk1ODI0MzkzLCJleHAiOjE3MjczNjAzOTN9.IIMx1Zg5Vbfniiecnx6SuXAK9UjnonxQcr9LENSEhRM&t=2023-09-27T14%3A19%3A48.828Z', max_length=500, null=True),
        ),
    ]
