# Generated by Django 4.2.5 on 2023-10-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ambiance_image_url_category_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiance',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='color',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='furnituretype',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='option',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='revetement',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='type',
            name='image_url',
        ),
        migrations.AddField(
            model_name='ambiance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='furnituretype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='revetement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
