# Generated by Django 4.2.5 on 2023-10-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_ambiance_image_url_remove_category_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='category',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='type',
        ),
        migrations.AlterField(
            model_name='ambiance',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.type'),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='ambiance',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.ambiance'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='furnitures',
            field=models.ManyToManyField(blank=True, related_name='orders', to='main.furniture'),
        ),
        migrations.AlterField(
            model_name='order',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='orders', to='main.option'),
        ),
        migrations.AlterField(
            model_name='order',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='orders', to='main.question'),
        ),
        migrations.AlterField(
            model_name='order',
            name='revetment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.revetement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.type'),
        ),
    ]
