# Generated by Django 4.2.5 on 2023-10-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_furniture_category_remove_furniture_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=''),
        ),
    ]
