# Generated by Django 4.2.5 on 2023-10-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ambiance_image_url_furniture_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiance',
            name='image_url',
            field=models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/public/dzeko_server_images/images.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/public/dzeko_server_images/images.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='image_url',
            field=models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/public/dzeko_server_images/images.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='furnituretype',
            name='image_url',
            field=models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/public/dzeko_server_images/images.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_url',
            field=models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/public/dzeko_server_images/images.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='image_url',
            field=models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/public/dzeko_server_images/images.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='revetement',
            name='image_url',
            field=models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/public/dzeko_server_images/images.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='image_url',
            field=models.URLField(blank=True, default='https://dlomnkdfvdzwzajbgpxu.supabase.co/storage/v1/object/public/dzeko_server_images/images.jpg', max_length=500, null=True),
        ),
    ]
