# Generated by Django 4.2.5 on 2023-10-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ambiance_image_url_alter_category_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
