# Generated by Django 4.2.5 on 2023-12-23 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_order_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='images',
        ),
        migrations.AddField(
            model_name='order',
            name='imageUrls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
