# Generated by Django 4.2.5 on 2023-12-23 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_order_images_order_imageurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='palette',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.palette'),
            preserve_default=False,
        ),
    ]
